### ISSUE TITLE
Maven 1.1.7 发布失败

### ISSUE THREAD

**Issue by Chen-Xi-g** [6tail/tyme4j#12]
1.1.7版本在maven中似乎发布失败了，使用Gradle无法引用。

**Maven信息**
![image](https://github.com/user-attachments/assets/c9cb8ffe-48de-4446-84dd-3924ea903330)

**1.1.6 Maven信息**
![image](https://github.com/user-attachments/assets/4e7777e4-c837-4d39-8bea-b8b30a46e544)

**Comment by 6tail** [comment]
已重推。
