### ISSUE TITLE
Tyme工具类问题

### ISSUE THREAD

**Issue by xiaokuihua2333** [6tail/tyme4j#9]
作者你好, 请问Tyme的Java版本, 怎么像Lunar一样, 获取某年所有节假日, 和下一个节假日

**Comment by 6tail** [comment]
一般情况下，1月1日一定是元旦的法定假日，所以可以LegalHoliday.fromYmd(年, 1, 1)得到元旦，然后循环调用next(1)得到下一个假日，直到跨年。

**Comment by xiaokuihua2333** [comment]
好的, 谢谢
